import image6 from "./assets/6.webp";
import image7 from "./assets/7.webp";
import image8 from "./assets/8.webp";
import image9 from "./assets/9.png";
import image10 from "./assets/10.webp";
import image11 from "./assets/11.jpeg";
import image12 from "./assets/12.avif";
import image13 from "./assets/13.avif";
import image14 from "./assets/14.jpg";
import item1 from "./assets/item1.jpg";
import item2 from "./assets/item2.jpg";
import item3 from "./assets/item3.jpg";
import item4 from "./assets/item4.jpg";
import output1 from "./assets/output1.jpg";
import output2 from "./assets/output2.jpg";
import output3 from "./assets/output3.jpg";
import output4 from "./assets/output4.jpg";

const image0 =
  "https://m.media-amazon.com/images/I/71cTIFxFDGL._SY741._SX._UX._SY._UY_.jpg";
const image1 =
  "https://m.media-amazon.com/images/I/71cTIFxFDGL._SY741._SX._UX._SY._UY_.jpg";
const image2 =
  "https://m.media-amazon.com/images/I/619yurnJjTL._SX569._SX._UX._SY._UY_.jpg";
const image3 =
  "https://m.media-amazon.com/images/I/81yGURqw25L._SX569._SX._UX._SY._UY_.jpg";
const image4 = "https://m.media-amazon.com/images/I/81diI+5cpAL._UX569_.jpg";
const image5 = "https://m.media-amazon.com/images/I/61WRDFg6EPL._UX679_.jpg";

const productList = {
  data: [
    {
      allCollections: [
        {
          itemImage:
            "https://m.media-amazon.com/images/I/71cTIFxFDGL._SY741._SX._UX._SY._UY_.jpg",
          outputImage: "",
        },
        {
          itemImage:
            "https://m.media-amazon.com/images/I/71CWdt8HviL._SY741._SX._UX._SY._UY_.jpg",
          outputImage: "",
        },
        {
          itemImage:
            "https://m.media-amazon.com/images/I/71l-IzX+gFL._SY741._SX._UX._SY._UY_.jpg",
          outputImage: "",
        },
        {
          itemImage:
            "https://m.media-amazon.com/images/I/81cIJ3UWgCL._SY741._SX._UX._SY._UY_.jpg",
          outputImage: "",
        },
        {
          itemImage:
            "https://m.media-amazon.com/images/I/81cIJ3UWgCL._SY741._SX._UX._SY._UY_.jpg",
          outputImage: "",
        },
        {
          itemImage:
            "https://m.media-amazon.com/images/I/71KHlnX53QL._SY741._SX._UX._SY._UY_.jpg",
          outputImage: "",
        },
        {
          itemImage:
            "https://m.media-amazon.com/images/I/71EooTjPEgL._SY741._SX._UX._SY._UY_.jpg",
          outputImage: "",
        },
      ],
      id: "prod_RyWOwmakAwnEa2",
      created: 1606298235,
      updated: 1606298235,
      active: true,
      permalink: "JjiTfp",
      name: "XPIOR",
      description: "<p></p><p>Black stove-top kettle</p><p></p>",
      price: {
        raw: 45.5,
        formatted: "45.50",
        formatted_with_symbol: "$45.50",
        formatted_with_code: "45.50 USD",
      },
      sku: null,
      sort_order: 0,
      seo: {
        title: null,
        description: null,
      },
      thank_you_url: null,
      meta: null,
      conditionals: {
        is_active: true,
        is_tax_exempt: false,
        is_pay_what_you_want: false,
        is_sold_out: false,
        has_digital_delivery: false,
        has_physical_delivery: true,
        has_images: true,
        collects_fullname: false,
        collects_shipping_address: true,
        collects_billing_address: false,
        has_video: false,
        has_rich_embed: false,
        is_free: false,
        collects_extrafields: false,
        is_quantity_limited: false,
      },
      is: {
        active: true,
        tax_exempt: false,
        pay_what_you_want: false,
        sold_out: false,
        free: false,
        quantity_limited: false,
      },
      has: {
        digital_delivery: false,
        physical_delivery: true,
        images: true,
      },
      collects: {
        fullname: false,
        shipping_address: true,
        billing_address: false,
        extrafields: false,
      },
      checkout_url: {
        checkout: "https://checkout.chec.io/JjiTfp?checkout=true",
        display: "https://checkout.chec.io/JjiTfp",
      },
      media: {
        type: "image",
        source: image0,
        asset_id: "ast_r2LM5QDa2oZV1g",
      },
      quantity: 0,
      categories: [],
      image: {
        id: "ast_r2LM5QDa2oZV1g",
        url: "https://cdn.chec.io/merchants/19661/assets/tv2wubQUhhbW1qAl|Screenshot 2020-11-25 at 10.56.41.png",
        description: null,
        is_image: true,
        filename: "Screenshot 2020-11-25 at 10.56.41.png",
        file_size: 50611,
        file_extension: "png",
        image_dimensions: {
          width: 436,
          height: 244,
        },
        meta: [],
        created_at: 1606298206,
        updated_at: 1606298209,
      },
      variant_groups: [],
      assets: [
        {
          id: "ast_r2LM5QDa2oZV1g",
          url: "https://cdn.chec.io/merchants/19661/assets/tv2wubQUhhbW1qAl|Screenshot 2020-11-25 at 10.56.41.png",
          description: null,
          is_image: true,
          filename: "Screenshot 2020-11-25 at 10.56.41.png",
          file_size: 50611,
          file_extension: "png",
          image_dimensions: {
            width: 436,
            height: 244,
          },
          meta: [],
          created_at: 1606298206,
          updated_at: 1606298209,
        },
        {
          id: "ast_r2LM5QDa2oZV1g",
          url: "https://cdn.chec.io/merchants/19661/assets/tv2wubQUhhbW1qAl|Screenshot 2020-11-25 at 10.56.41.png",
          description: null,
          is_image: true,
          filename: "Screenshot 2020-11-25 at 10.56.41.png",
          file_size: 50611,
          file_extension: "png",
          image_dimensions: {
            width: 436,
            height: 244,
          },
          meta: [],
          created_at: 1606298206,
          updated_at: 1606298209,
        },
      ],
      attributes: [],
      related_products: [],
      extrafields: [],
      variants: [],
    },
    {
      allCollections: [
        {
          itemImage:
            "https://m.media-amazon.com/images/I/61+t3qyK3wL._UX569_.jpg",
          outputImage: "",
        },
        {
          itemImage:
            "https://m.media-amazon.com/images/I/619yurnJjTL._SX569._SX._UX._SY._UY_.jpg",
          outputImage: "",
        },
      ],
      id: "prod_Kvg9l6Xrpo1bB7",
      created: 1606298293,
      updated: 1606298293,
      active: true,
      permalink: "HOYz8I",
      name: "ELECTRO",
      description: "<p></p><p>Book on grid systems</p><p></p>",
      price: {
        raw: 13.5,
        formatted: "13.50",
        formatted_with_symbol: "$13.50",
        formatted_with_code: "13.50 USD",
      },
      sku: null,
      sort_order: 0,
      seo: {
        title: null,
        description: null,
      },
      thank_you_url: null,
      meta: null,
      conditionals: {
        is_active: true,
        is_tax_exempt: false,
        is_pay_what_you_want: false,
        is_sold_out: false,
        has_digital_delivery: false,
        has_physical_delivery: true,
        has_images: true,
        collects_fullname: false,
        collects_shipping_address: true,
        collects_billing_address: false,
        has_video: false,
        has_rich_embed: false,
        is_free: false,
        collects_extrafields: false,
        is_quantity_limited: false,
      },
      is: {
        active: true,
        tax_exempt: false,
        pay_what_you_want: false,
        sold_out: false,
        free: false,
        quantity_limited: false,
      },
      has: {
        digital_delivery: false,
        physical_delivery: true,
        images: true,
      },
      collects: {
        fullname: false,
        shipping_address: true,
        billing_address: false,
        extrafields: false,
      },
      checkout_url: {
        checkout: "https://checkout.chec.io/HOYz8I?checkout=true",
        display: "https://checkout.chec.io/HOYz8I",
      },
      media: {
        type: "image",
        source: image2,
        asset_id: "ast_NXELwj6bzw3A4p",
      },
      quantity: 0,
      categories: [],
      image: {
        id: "ast_NXELwj6bzw3A4p",
        url: "https://cdn.chec.io/merchants/19661/assets/YRVZPLtp0ascAs1G|Screenshot 2020-11-25 at 10.57.49.png",
        description: null,
        is_image: true,
        filename: "Screenshot 2020-11-25 at 10.57.49.png",
        file_size: 69746,
        file_extension: "png",
        image_dimensions: {
          width: 434,
          height: 246,
        },
        meta: [],
        created_at: 1606298272,
        updated_at: 1606298273,
      },
      variant_groups: [],
      assets: [
        {
          id: "ast_NXELwj6bzw3A4p",
          url: "https://cdn.chec.io/merchants/19661/assets/YRVZPLtp0ascAs1G|Screenshot 2020-11-25 at 10.57.49.png",
          description: null,
          is_image: true,
          filename: "Screenshot 2020-11-25 at 10.57.49.png",
          file_size: 69746,
          file_extension: "png",
          image_dimensions: {
            width: 434,
            height: 246,
          },
          meta: [],
          created_at: 1606298272,
          updated_at: 1606298273,
        },
        {
          id: "ast_NXELwj6bzw3A4p",
          url: "https://cdn.chec.io/merchants/19661/assets/YRVZPLtp0ascAs1G|Screenshot 2020-11-25 at 10.57.49.png",
          description: null,
          is_image: true,
          filename: "Screenshot 2020-11-25 at 10.57.49.png",
          file_size: 69746,
          file_extension: "png",
          image_dimensions: {
            width: 434,
            height: 246,
          },
          meta: [],
          created_at: 1606298272,
          updated_at: 1606298273,
        },
      ],
      attributes: [],
      related_products: [],
      extrafields: [],
      variants: [],
    },
    {
      allCollections: [
        {
          itemImage:
            "https://m.media-amazon.com/images/I/81yGURqw25L._SX569._SX._UX._SY._UY_.jpg",
          outputImage: "",
        },
        {
          itemImage:
            "https://m.media-amazon.com/images/I/71KqzZyNlEL._UX569_.jpg",
          outputImage: "",
        },
      ],
      id: "prod_NqKE50vEgwdgBL",
      created: 1606298328,
      updated: 1606298328,
      active: true,
      permalink: "ilJcYE",
      name: "Clothin",
      description: "<p></p><p>Whole bean espresso can</p><p></p>",
      price: {
        raw: 7.5,
        formatted: "7.50",
        formatted_with_symbol: "$7.50",
        formatted_with_code: "7.50 USD",
      },
      sku: null,
      sort_order: 0,
      seo: {
        title: null,
        description: null,
      },
      thank_you_url: null,
      meta: null,
      conditionals: {
        is_active: true,
        is_tax_exempt: false,
        is_pay_what_you_want: false,
        is_sold_out: false,
        has_digital_delivery: false,
        has_physical_delivery: true,
        has_images: true,
        collects_fullname: false,
        collects_shipping_address: true,
        collects_billing_address: false,
        has_video: false,
        has_rich_embed: false,
        is_free: false,
        collects_extrafields: false,
        is_quantity_limited: false,
      },
      is: {
        active: true,
        tax_exempt: false,
        pay_what_you_want: false,
        sold_out: false,
        free: false,
        quantity_limited: false,
      },
      has: {
        digital_delivery: false,
        physical_delivery: true,
        images: true,
      },
      collects: {
        fullname: false,
        shipping_address: true,
        billing_address: false,
        extrafields: false,
      },
      checkout_url: {
        checkout: "https://checkout.chec.io/ilJcYE?checkout=true",
        display: "https://checkout.chec.io/ilJcYE",
      },
      media: {
        type: "image",
        source: image3,
        asset_id: "ast_L1vOoZ2x2oRa8Z",
      },
      quantity: 0,
      categories: [],
      image: {
        id: "ast_L1vOoZ2x2oRa8Z",
        url: "https://cdn.chec.io/merchants/19661/assets/HLByCJoJDfQHRtuH|Screenshot 2020-11-25 at 10.58.24.png",
        description: null,
        is_image: true,
        filename: "Screenshot 2020-11-25 at 10.58.24.png",
        file_size: 30287,
        file_extension: "png",
        image_dimensions: {
          width: 432,
          height: 244,
        },
        meta: [],
        created_at: 1606298307,
        updated_at: 1606298308,
      },
      variant_groups: [],
      assets: [
        {
          id: "ast_L1vOoZ2x2oRa8Z",
          url: "https://cdn.chec.io/merchants/19661/assets/HLByCJoJDfQHRtuH|Screenshot 2020-11-25 at 10.58.24.png",
          description: null,
          is_image: true,
          filename: "Screenshot 2020-11-25 at 10.58.24.png",
          file_size: 30287,
          file_extension: "png",
          image_dimensions: {
            width: 432,
            height: 244,
          },
          meta: [],
          created_at: 1606298307,
          updated_at: 1606298308,
        },
        {
          id: "ast_L1vOoZ2x2oRa8Z",
          url: "https://cdn.chec.io/merchants/19661/assets/HLByCJoJDfQHRtuH|Screenshot 2020-11-25 at 10.58.24.png",
          description: null,
          is_image: true,
          filename: "Screenshot 2020-11-25 at 10.58.24.png",
          file_size: 30287,
          file_extension: "png",
          image_dimensions: {
            width: 432,
            height: 244,
          },
          meta: [],
          created_at: 1606298307,
          updated_at: 1606298308,
        },
      ],
      attributes: [],
      related_products: [],
      extrafields: [],
      variants: [],
    },
    {
      allCollections: [
        {
          itemImage:
          "https://m.media-amazon.com/images/I/81diI+5cpAL._UX569_.jpg",
          outputImage: "",
        },
        {
          itemImage:
          "https://m.media-amazon.com/images/I/81wauBJCA3L._SX569._SX._UX._SY._UY_.jpg",
          outputImage: "",
        },
        {
          itemImage:
          "https://m.media-amazon.com/images/I/81wV+cPlxcL._SX569._SX._UX._SY._UY_.jpg",
          outputImage: "",
        },
      ],
      id: "prod_kpnNwAQPkwmXB3",
      created: 1606298378,
      updated: 1606298378,
      active: true,
      permalink: "IiTKVC",
      name: "Bowrain",
      description: "<p></p><p>Wooden table lamp</p><p></p>",
      price: {
        raw: 90,
        formatted: "90.00",
        formatted_with_symbol: "$90.00",
        formatted_with_code: "90.00 USD",
      },
      sku: null,
      sort_order: 0,
      seo: {
        title: null,
        description: null,
      },
      thank_you_url: null,
      meta: null,
      conditionals: {
        is_active: true,
        is_tax_exempt: false,
        is_pay_what_you_want: false,
        is_sold_out: false,
        has_digital_delivery: false,
        has_physical_delivery: true,
        has_images: true,
        collects_fullname: false,
        collects_shipping_address: true,
        collects_billing_address: false,
        has_video: false,
        has_rich_embed: false,
        is_free: false,
        collects_extrafields: false,
        is_quantity_limited: false,
      },
      is: {
        active: true,
        tax_exempt: false,
        pay_what_you_want: false,
        sold_out: false,
        free: false,
        quantity_limited: false,
      },
      has: {
        digital_delivery: false,
        physical_delivery: true,
        images: true,
      },
      collects: {
        fullname: false,
        shipping_address: true,
        billing_address: false,
        extrafields: false,
      },
      checkout_url: {
        checkout: "https://checkout.chec.io/IiTKVC?checkout=true",
        display: "https://checkout.chec.io/IiTKVC",
      },
      media: {
        type: "image",
        source: image4,
        asset_id: "ast_0YnEoqKbqle7P6",
      },
      quantity: 0,
      categories: [],
      image: {
        id: "ast_0YnEoqKbqle7P6",
        url: "https://cdn.chec.io/merchants/19661/assets/AtrQpmVYbw9jwdf7|Screenshot 2020-11-25 at 10.59.19.png",
        description: null,
        is_image: true,
        filename: "Screenshot 2020-11-25 at 10.59.19.png",
        file_size: 31216,
        file_extension: "png",
        image_dimensions: {
          width: 432,
          height: 246,
        },
        meta: [],
        created_at: 1606298363,
        updated_at: 1606298364,
      },
      variant_groups: [],
      assets: [
        {
          id: "ast_0YnEoqKbqle7P6",
          url: "https://cdn.chec.io/merchants/19661/assets/AtrQpmVYbw9jwdf7|Screenshot 2020-11-25 at 10.59.19.png",
          description: null,
          is_image: true,
          filename: "Screenshot 2020-11-25 at 10.59.19.png",
          file_size: 31216,
          file_extension: "png",
          image_dimensions: {
            width: 432,
            height: 246,
          },
          meta: [],
          created_at: 1606298363,
          updated_at: 1606298364,
        },
        {
          id: "ast_0YnEoqKbqle7P6",
          url: "https://cdn.chec.io/merchants/19661/assets/AtrQpmVYbw9jwdf7|Screenshot 2020-11-25 at 10.59.19.png",
          description: null,
          is_image: true,
          filename: "Screenshot 2020-11-25 at 10.59.19.png",
          file_size: 31216,
          file_extension: "png",
          image_dimensions: {
            width: 432,
            height: 246,
          },
          meta: [],
          created_at: 1606298363,
          updated_at: 1606298364,
        },
      ],
      attributes: [],
      related_products: [],
      extrafields: [],
      variants: [],
    },
    {
      allCollections: [
        { itemImage: item1, outputImage: output1 },
        { itemImage: item2, outputImage: output2 },
        { itemImage: item3, outputImage: output3 },
        { itemImage: item4, outputImage: output4 },
      ],
      id: "prod_8XO3wpXj4wYAzQ",
      created: 1606298406,
      updated: 1606298406,
      active: true,
      permalink: "Nb0dQ0",
      name: "XPIOR",
      description: "<p></p><p>Seafoam wireless headphones</p><p></p>",
      price: {
        raw: 60,
        formatted: "60.00",
        formatted_with_symbol: "$60.00",
        formatted_with_code: "60.00 USD",
      },
      sku: null,
      sort_order: 0,
      seo: {
        title: null,
        description: null,
      },
      thank_you_url: null,
      meta: null,
      conditionals: {
        is_active: true,
        is_tax_exempt: false,
        is_pay_what_you_want: false,
        is_sold_out: false,
        has_digital_delivery: false,
        has_physical_delivery: true,
        has_images: true,
        collects_fullname: false,
        collects_shipping_address: true,
        collects_billing_address: false,
        has_video: false,
        has_rich_embed: false,
        is_free: false,
        collects_extrafields: false,
        is_quantity_limited: false,
      },
      is: {
        active: true,
        tax_exempt: false,
        pay_what_you_want: false,
        sold_out: false,
        free: false,
        quantity_limited: false,
      },
      has: {
        digital_delivery: false,
        physical_delivery: true,
        images: true,
      },
      collects: {
        fullname: false,
        shipping_address: true,
        billing_address: false,
        extrafields: false,
      },
      checkout_url: {
        checkout: "https://checkout.chec.io/Nb0dQ0?checkout=true",
        display: "https://checkout.chec.io/Nb0dQ0",
      },
      media: {
        type: "image",
        source: image5,
        asset_id: "ast_kd6Ll22z0lV2mj",
      },
      quantity: 0,
      categories: [],
      image: {
        id: "ast_kd6Ll22z0lV2mj",
        url: "https://cdn.chec.io/merchants/19661/assets/NwVTaC1cAey9qtaj|Screenshot 2020-11-25 at 10.59.48.png",
        description: null,
        is_image: true,
        filename: "Screenshot 2020-11-25 at 10.59.48.png",
        file_size: 57608,
        file_extension: "png",
        image_dimensions: {
          width: 436,
          height: 243,
        },
        meta: [],
        created_at: 1606298392,
        updated_at: 1606298394,
      },
      variant_groups: [],
      assets: [
        {
          id: "ast_kd6Ll22z0lV2mj",
          url: "https://cdn.chec.io/merchants/19661/assets/NwVTaC1cAey9qtaj|Screenshot 2020-11-25 at 10.59.48.png",
          description: null,
          is_image: true,
          filename: "Screenshot 2020-11-25 at 10.59.48.png",
          file_size: 57608,
          file_extension: "png",
          image_dimensions: {
            width: 436,
            height: 243,
          },
          meta: [],
          created_at: 1606298392,
          updated_at: 1606298394,
        },
        {
          id: "ast_kd6Ll22z0lV2mj",
          url: "https://cdn.chec.io/merchants/19661/assets/NwVTaC1cAey9qtaj|Screenshot 2020-11-25 at 10.59.48.png",
          description: null,
          is_image: true,
          filename: "Screenshot 2020-11-25 at 10.59.48.png",
          file_size: 57608,
          file_extension: "png",
          image_dimensions: {
            width: 436,
            height: 243,
          },
          meta: [],
          created_at: 1606298392,
          updated_at: 1606298394,
        },
      ],
      attributes: [],
      related_products: [],
      extrafields: [],
      variants: [],
    },
    {
      id: "prod_bO6J5aqVy5EjpK",
      created: 1606298429,
      updated: 1606298436,
      active: true,
      permalink: "1Dzo37",
      name: "ELECTRO",
      description: "<p></p><p>Black roll-top backpack</p><p></p>",
      price: {
        raw: 80,
        formatted: "80.00",
        formatted_with_symbol: "$80.00",
        formatted_with_code: "80.00 USD",
      },
      sku: null,
      sort_order: 0,
      seo: {
        title: null,
        description: null,
      },
      thank_you_url: null,
      meta: null,
      conditionals: {
        is_active: true,
        is_tax_exempt: false,
        is_pay_what_you_want: false,
        is_sold_out: false,
        has_digital_delivery: false,
        has_physical_delivery: true,
        has_images: true,
        collects_fullname: false,
        collects_shipping_address: true,
        collects_billing_address: false,
        has_video: false,
        has_rich_embed: false,
        is_free: false,
        collects_extrafields: false,
        is_quantity_limited: false,
      },
      is: {
        active: true,
        tax_exempt: false,
        pay_what_you_want: false,
        sold_out: false,
        free: false,
        quantity_limited: false,
      },
      has: {
        digital_delivery: false,
        physical_delivery: true,
        images: true,
      },
      collects: {
        fullname: false,
        shipping_address: true,
        billing_address: false,
        extrafields: false,
      },
      checkout_url: {
        checkout: "https://checkout.chec.io/1Dzo37?checkout=true",
        display: "https://checkout.chec.io/1Dzo37",
      },
      media: {
        type: "image",
        source: image6,
        asset_id: "ast_4OANwRPrb5vYL8",
      },
      quantity: 0,
      categories: [],
      image: {
        id: "ast_4OANwRPrb5vYL8",
        url: "https://cdn.chec.io/merchants/19661/assets/WGkKDasZr7W5RVC2|Screenshot 2020-11-25 at 11.00.11.png",
        description: null,
        is_image: true,
        filename: "Screenshot 2020-11-25 at 11.00.11.png",
        file_size: 49392,
        file_extension: "png",
        image_dimensions: {
          width: 436,
          height: 242,
        },
        meta: [],
        created_at: 1606298416,
        updated_at: 1606298419,
      },
      variant_groups: [],
      assets: [
        {
          id: "ast_4OANwRPrb5vYL8",
          url: "https://cdn.chec.io/merchants/19661/assets/WGkKDasZr7W5RVC2|Screenshot 2020-11-25 at 11.00.11.png",
          description: null,
          is_image: true,
          filename: "Screenshot 2020-11-25 at 11.00.11.png",
          file_size: 49392,
          file_extension: "png",
          image_dimensions: {
            width: 436,
            height: 242,
          },
          meta: [],
          created_at: 1606298416,
          updated_at: 1606298419,
        },
        {
          id: "ast_4OANwRPrb5vYL8",
          url: "https://cdn.chec.io/merchants/19661/assets/WGkKDasZr7W5RVC2|Screenshot 2020-11-25 at 11.00.11.png",
          description: null,
          is_image: true,
          filename: "Screenshot 2020-11-25 at 11.00.11.png",
          file_size: 49392,
          file_extension: "png",
          image_dimensions: {
            width: 436,
            height: 242,
          },
          meta: [],
          created_at: 1606298416,
          updated_at: 1606298419,
        },
      ],
      attributes: [],
      related_products: [],
      extrafields: [],
      variants: [],
    },
    {
      id: "prod_A12JwrGqXoPjnk",
      created: 1606298475,
      updated: 1606303804,
      active: true,
      permalink: "8QCsdn",
      name: "Bowrain",
      description: "<p></p><p>Black magic keyboard</p><p></p>",
      price: {
        raw: 65,
        formatted: "65.00",
        formatted_with_symbol: "$65.00",
        formatted_with_code: "65.00 USD",
      },
      sku: null,
      sort_order: 0,
      seo: {
        title: null,
        description: null,
      },
      thank_you_url: null,
      meta: null,
      conditionals: {
        is_active: true,
        is_tax_exempt: false,
        is_pay_what_you_want: false,
        is_sold_out: false,
        has_digital_delivery: false,
        has_physical_delivery: true,
        has_images: true,
        collects_fullname: false,
        collects_shipping_address: true,
        collects_billing_address: false,
        has_video: false,
        has_rich_embed: false,
        is_free: false,
        collects_extrafields: false,
        is_quantity_limited: false,
      },
      is: {
        active: true,
        tax_exempt: false,
        pay_what_you_want: false,
        sold_out: false,
        free: false,
        quantity_limited: false,
      },
      has: {
        digital_delivery: false,
        physical_delivery: true,
        images: true,
      },
      collects: {
        fullname: false,
        shipping_address: true,
        billing_address: false,
        extrafields: false,
      },
      checkout_url: {
        checkout: "https://checkout.chec.io/8QCsdn?checkout=true",
        display: "https://checkout.chec.io/8QCsdn",
      },
      media: {
        type: "image",
        source: image9,
        asset_id: "ast_yA6nldMNzwEWbz",
      },
      quantity: 0,
      categories: [],
      image: {
        id: "ast_yA6nldMNzwEWbz",
        url: "https://cdn.chec.io/merchants/19661/assets/H4khxFAmm8BOxSOZ|Screenshot 2020-11-25 at 11.00.51.png",
        description: null,
        is_image: true,
        filename: "Screenshot 2020-11-25 at 11.00.51.png",
        file_size: 43633,
        file_extension: "png",
        image_dimensions: {
          width: 434,
          height: 240,
        },
        meta: [],
        created_at: 1606298455,
        updated_at: 1606298457,
      },
      variant_groups: [],
      assets: [
        {
          id: "ast_yA6nldMNzwEWbz",
          url: "https://cdn.chec.io/merchants/19661/assets/H4khxFAmm8BOxSOZ|Screenshot 2020-11-25 at 11.00.51.png",
          description: null,
          is_image: true,
          filename: "Screenshot 2020-11-25 at 11.00.51.png",
          file_size: 43633,
          file_extension: "png",
          image_dimensions: {
            width: 434,
            height: 240,
          },
          meta: [],
          created_at: 1606298455,
          updated_at: 1606298457,
        },
        {
          id: "ast_yA6nldMNzwEWbz",
          url: "https://cdn.chec.io/merchants/19661/assets/H4khxFAmm8BOxSOZ|Screenshot 2020-11-25 at 11.00.51.png",
          description: null,
          is_image: true,
          filename: "Screenshot 2020-11-25 at 11.00.51.png",
          file_size: 43633,
          file_extension: "png",
          image_dimensions: {
            width: 434,
            height: 240,
          },
          meta: [],
          created_at: 1606298455,
          updated_at: 1606298457,
        },
      ],
      attributes: [],
      related_products: [],
      extrafields: [],
      variants: [],
    },
    {
      id: "prod_Op1YoVq3dwXLv9",
      created: 1606298502,
      updated: 1606298502,
      active: true,
      permalink: "WtPYRe",
      name: "Pro",
      description: "<p></p><p>Black magic mouse</p><p></p>",
      price: {
        raw: 50,
        formatted: "50.00",
        formatted_with_symbol: "$50.00",
        formatted_with_code: "50.00 USD",
      },
      sku: null,
      sort_order: 0,
      seo: {
        title: null,
        description: null,
      },
      thank_you_url: null,
      meta: null,
      conditionals: {
        is_active: true,
        is_tax_exempt: false,
        is_pay_what_you_want: false,
        is_sold_out: false,
        has_digital_delivery: false,
        has_physical_delivery: true,
        has_images: true,
        collects_fullname: false,
        collects_shipping_address: true,
        collects_billing_address: false,
        has_video: false,
        has_rich_embed: false,
        is_free: false,
        collects_extrafields: false,
        is_quantity_limited: false,
      },
      is: {
        active: true,
        tax_exempt: false,
        pay_what_you_want: false,
        sold_out: false,
        free: false,
        quantity_limited: false,
      },
      has: {
        digital_delivery: false,
        physical_delivery: true,
        images: true,
      },
      collects: {
        fullname: false,
        shipping_address: true,
        billing_address: false,
        extrafields: false,
      },
      checkout_url: {
        checkout: "https://checkout.chec.io/WtPYRe?checkout=true",
        display: "https://checkout.chec.io/WtPYRe",
      },
      media: {
        type: "image",
        source: image7,
        asset_id: "ast_VPvL5zPB3wAQkX",
      },
      quantity: 0,
      categories: [],
      image: {
        id: "ast_VPvL5zPB3wAQkX",
        url: "https://cdn.chec.io/merchants/19661/assets/VFgCKovPcmNWYm4G|Screenshot 2020-11-25 at 11.01.24.png",
        description: null,
        is_image: true,
        filename: "Screenshot 2020-11-25 at 11.01.24.png",
        file_size: 22698,
        file_extension: "png",
        image_dimensions: {
          width: 434,
          height: 242,
        },
        meta: [],
        created_at: 1606298486,
        updated_at: 1606298487,
      },
      variant_groups: [],
      assets: [
        {
          id: "ast_VPvL5zPB3wAQkX",
          url: "https://cdn.chec.io/merchants/19661/assets/VFgCKovPcmNWYm4G|Screenshot 2020-11-25 at 11.01.24.png",
          description: null,
          is_image: true,
          filename: "Screenshot 2020-11-25 at 11.01.24.png",
          file_size: 22698,
          file_extension: "png",
          image_dimensions: {
            width: 434,
            height: 242,
          },
          meta: [],
          created_at: 1606298486,
          updated_at: 1606298487,
        },
        {
          id: "ast_VPvL5zPB3wAQkX",
          url: "https://cdn.chec.io/merchants/19661/assets/VFgCKovPcmNWYm4G|Screenshot 2020-11-25 at 11.01.24.png",
          description: null,
          is_image: true,
          filename: "Screenshot 2020-11-25 at 11.01.24.png",
          file_size: 22698,
          file_extension: "png",
          image_dimensions: {
            width: 434,
            height: 242,
          },
          meta: [],
          created_at: 1606298486,
          updated_at: 1606298487,
        },
      ],
      attributes: [],
      related_products: [],
      extrafields: [],
      variants: [],
    },
  ],
  meta: {
    pagination: {
      total: 8,
      count: 8,
      per_page: 20,
      current_page: 1,
      total_pages: 1,
      links: {},
    },
  },
};

export default productList;
